import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import AuthProvider from '../app/components/AuthProvider';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={inter.className}>
        <div className="flex flex-col min-h-dvh">
          <header className="bg-background border-b px-4 md:px-6 flex items-center h-14 justify-between">
            <Link href="#" className="flex items-center" prefetch={false}>
              <span className="sr-only">Acme Inc</span>
            </Link>
            <nav className="hidden md:flex gap-6">
              <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
                Home
              </Link>
              <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
                About
              </Link>
              <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
                Services
              </Link>
              <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
                Contact
              </Link>
            </nav>
          </header>
          <main className="flex-1">
          <AuthProvider>
            {children}
          </AuthProvider>

          </main>
          <footer className="bg-muted p-6 md:p-8 flex flex-col md:flex-row items-center md:justify-between gap-4">
            <div className="text-xs text-muted-foreground">&copy; 2024 Acme Inc. All rights reserved.</div>
            <nav className="flex gap-4 md:gap-6">
              <Link href="#" className="text-xs hover:underline underline-offset-4" prefetch={false}>
                Terms of Service
              </Link>
              <Link href="#" className="text-xs hover:underline underline-offset-4" prefetch={false}>
                Privacy Policy
              </Link>
              <Link href="#" className="text-xs hover:underline underline-offset-4" prefetch={false}>
                Contact Us
              </Link>
            </nav>
          </footer>
        </div>
      </body>
    </html>
  );
}
